// make_hero.mjs — precompute the landing page's hero: one lottery draw of both rules over all three
// entry grades, reduced to what a small picture needs. The landing page must stay light, so it ships
// this file instead of the market and the engine.
//   node tools/make_hero.mjs      ->  data/hero_lines.json
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildMarket, simulate } from "../engine/engine.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.join(here, "..", "data");
const read = p => JSON.parse(fs.readFileSync(path.join(dataDir, p), "utf8"));
const GRADES = [2, 3, 4], SEED = 7, SAMPLE = 560;
const r5 = x => Math.round(x * 1e5) / 1e5;

const schoolsJson = read("schools.json"), calib = read("calibration.json");
const byId = new Map(schoolsJson.schools.map(s => [s.id, s]));

// One union of schools across the three grades; a school's radius uses its largest grade offering.
const union = [], uIdx = new Map();
for (const g of GRADES)
  for (const id of read(`applicants_g${g}.json`).schools)
    if (!uIdx.has(id)) { uIdx.set(id, union.length); union.push(id); }

// A spread-out sample, drawn from each grade in proportion to its size.
let s = 20260905;
const rnd = () => ((s = (s * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff);
const shuffled = n => {
  const a = Array.from({ length: n }, (_, i) => i);
  for (let i = n - 1; i > 0; i--) { const j = Math.floor(rnd() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
  return a;
};

const homes = [], out = { dc: { s: [], c: [] }, da: { s: [], c: [] } };
const markets = GRADES.map(g => buildMarket(schoolsJson, read(`applicants_g${g}.json`)));
const total = markets.reduce((a, m) => a + m.n, 0);
for (const m of markets) {
  const res = simulate(m, { draws: 1, seed: SEED, rules: ["dc", "da"] });
  const take = Math.round(SAMPLE * m.n / total);
  for (const i of shuffled(m.n).slice(0, take).sort((a, b) => a - b)) {
    homes.push([r5(m.aLat[i]), r5(m.aLon[i])]);
    for (const rule of ["dc", "da"]) {
      const p = res.last[rule][i];
      out[rule].s.push(p < 0 ? -1 : uIdx.get(m.ids[p]));
      // 2 = the family's first choice, 1 = another school it listed, 0 = a school it never asked for
      out[rule].c.push(p < 0 ? 0 : m.rol[i][0] === p ? 2 : m.rol[i].includes(p) ? 1 : 0);
    }
  }
}

const seatsOf = id => Math.max(...Object.values(byId.get(id).grades).map(v => v.seats));
const data = {
  note: "One lottery draw of all three entry grades, sampled for the landing page's hero. Generated by tools/make_hero.mjs; the picture is the synthetic population, the shares in `paper` are the paper's.",
  grades: GRADES, seed: SEED, n: total, sample: homes.length,
  schools: union.map(id => [r5(byId.get(id).lat), r5(byId.get(id).lon), seatsOf(id)]),
  homes, dc: out.dc, da: out.da,
  paper: { dc: calib.targets.listed_dc, da: calib.targets.listed_da },
  synthetic: { dc: calib.pooled.dc.listed, da: calib.pooled.da.listed },
};
const file = path.join(dataDir, "hero_lines.json");
fs.writeFileSync(file, JSON.stringify(data));
const share = r => 100 * data[r].c.filter(x => x > 0).length / data[r].c.length;
console.log(`wrote data/hero_lines.json (${Math.round(fs.statSync(file).size / 1024)} KB): ` +
  `${union.length} schools, ${homes.length} of ${total} families sampled across grades ${GRADES.join("/")}; ` +
  `placed in a listed school — distance rule ${share("dc").toFixed(0)}%, DA ${share("da").toFixed(0)}% ` +
  `(whole market ${data.synthetic.dc.toFixed(1)}% / ${data.synthetic.da.toFixed(1)}%; paper ${data.paper.dc}% / ${data.paper.da}%)`);
